version: "2"
services:
  influxdb:
    image: influxdb
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=telegraf
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
      - INFLUXDB_HTTP_AUTH_ENABLED=true
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    links:
      - influxdb
  telegraf:
    image: telegraf:1.4
    ports:
      - "8125:8125/udp"
    volumes:
    - ./telegraf.conf:/etc/telegraf/telegraf.conf
    links:
      - influxdb
